// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpotPower.Infrastructure.Persistence;

#nullable disable

namespace SpotPower.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SpotPowerDbContext))]
    [Migration("20260719213139_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SpotPower.Core.AuctionPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceEurPerMwhPortugal")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceEurPerMwhSpain")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryDate", "Period")
                        .IsUnique();

                    b.ToTable("AuctionPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
